/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'departmentId', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare departmentId: number | null
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DepartmentSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = DepartmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'message', 'readAt', 'ticketId', 'title', 'type', 'updatedAt', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string | null
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare ticketId: number | null
  @column()
  declare title: string | null
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class TicketSchema extends BaseModel {
  static $columns = ['assigneeId', 'categoryId', 'closedAt', 'createdAt', 'departmentId', 'description', 'dueAt', 'id', 'number', 'priority', 'requesterId', 'status', 'title', 'updatedAt'] as const
  $columns = TicketSchema.$columns
  @column()
  declare assigneeId: number | null
  @column()
  declare categoryId: number | null
  @column.dateTime()
  declare closedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare departmentId: number | null
  @column()
  declare description: string | null
  @column.dateTime()
  declare dueAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare number: string
  @column()
  declare priority: string
  @column()
  declare requesterId: number
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
